allowBuilds:
  '@swc/core': true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - unrs-resolver
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
